const starterPrograms=[{name:'معسكر الابتكار المؤسسي',type:'برنامج',date:'2026-07-15',participants:64,trainer:'د. أحمد الحربي',response:84,score:4.8,status:'مكتمل'},{name:'ورشة نمذجة الأفكار',type:'ورشة عمل',date:'2026-07-10',participants:42,trainer:'أ. سارة الغامدي',response:76,score:4.6,status:'مكتمل'},{name:'جلسة حوارية مع رائد أعمال',type:'جلسة',date:'2026-07-06',participants:95,trainer:'م. خالد العمري',response:69,score:4.5,status:'مكتمل'},{name:'برنامج بناء المشاريع الناشئة',type:'برنامج',date:'2026-07-28',participants:50,trainer:'د. نورة الزهراني',response:0,score:'—',status:'قادم'},{name:'ورشة دراسة الجدوى',type:'ورشة عمل',date:'2026-08-02',participants:35,trainer:'أ. فيصل الشريف',response:0,score:'—',status:'قادم'}];
let programs=JSON.parse(localStorage.getItem('iec-programs')||'null')||starterPrograms;
const titles={dashboard:'لوحة المتابعة',programs:'البرامج والورش', 'new-program':'إضافة برنامج',evaluations:'التقييمات',reports:'التقارير',settings:'الإعدادات'};
const navItems=document.querySelectorAll('.nav-item');const views=document.querySelectorAll('.view');
function navigate(id){views.forEach(v=>v.classList.toggle('active-view',v.id===id));navItems.forEach(n=>n.classList.toggle('active',n.dataset.view===id));document.getElementById('pageTitle').textContent=titles[id]||'';document.getElementById('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});}
navItems.forEach(btn=>btn.addEventListener('click',()=>navigate(btn.dataset.view)));document.querySelectorAll('[data-go]').forEach(btn=>btn.addEventListener('click',()=>navigate(btn.dataset.go)));document.getElementById('menuBtn').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));
function statusClass(status){return status==='مكتمل'?'done':'upcoming'}
function formatDate(value){return new Intl.DateTimeFormat('ar-SA',{year:'numeric',month:'short',day:'numeric'}).format(new Date(value));}
function renderRecent(){document.getElementById('recentPrograms').innerHTML=programs.slice(0,5).map(p=>`<tr><td><strong>${p.name}</strong><br><small>${p.trainer}</small></td><td>${p.type}</td><td>${formatDate(p.date)}</td><td>${p.participants}</td><td>${p.response}%</td><td><span class="score">${p.score}</span></td><td><span class="status ${statusClass(p.status)}">${p.status}</span></td></tr>`).join('');document.getElementById('programCount').textContent=programs.length;}
function renderPrograms(list=programs){document.getElementById('programGrid').innerHTML=list.map((p,i)=>`<article class="program-card"><div class="program-card-top"><span class="type-chip">${p.type}</span><span class="status ${statusClass(p.status)}">${p.status}</span></div><h3>${p.name}</h3><p>المقدم: ${p.trainer}</p><p>التاريخ: ${formatDate(p.date)}</p><p>المشاركون: ${p.participants}</p><div class="program-card-footer"><span>الاستجابة ${p.response}%</span><span class="score">${p.score==='—'?'لم يبدأ':p.score+' / 5'}</span></div></article>`).join('')||'<div class="empty-state"><h2>لا توجد نتائج</h2><p>جرّب تغيير كلمات البحث أو التصفية.</p></div>'}
renderRecent();renderPrograms();
const search=document.getElementById('programSearch'),typeFilter=document.getElementById('typeFilter');function applyFilters(){const q=search.value.trim().toLowerCase(),type=typeFilter.value;renderPrograms(programs.filter(p=>(p.name+' '+p.trainer).toLowerCase().includes(q)&&(type==='all'||p.type===type)));}search.addEventListener('input',applyFilters);typeFilter.addEventListener('change',applyFilters);
document.getElementById('programForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const item={name:fd.get('name'),type:fd.get('type'),date:fd.get('date'),audience:fd.get('audience'),participants:Number(fd.get('participants')||0),organizer:fd.get('organizer'),trainer:fd.get('trainer'),response:0,score:'—',status:new Date(fd.get('date'))>new Date()?'قادم':'مكتمل'};programs.unshift(item);localStorage.setItem('iec-programs',JSON.stringify(programs));renderRecent();renderPrograms();e.currentTarget.reset();showToast('تم حفظ البرنامج وإنشاء رابط تقييم مبدئي');navigate('programs');});
const modal=document.getElementById('evaluationModal');document.getElementById('previewEvaluation').addEventListener('click',()=>modal.classList.add('show'));document.getElementById('closeModal').addEventListener('click',()=>modal.classList.remove('show'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('show')});document.querySelectorAll('.rating-row').forEach(row=>row.querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>{row.querySelectorAll('button').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected')})));
function showToast(message){const toast=document.getElementById('toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
