const DB_KEY='iec-platform-v2';
const questions=[['content','الرضا عن المحتوى'],['organization','الرضا عن التنظيم'],['trainer','تقييم المدرب أو مقدم الجلسة'],['goals','مدى تحقق الأهداف'],['benefit','الاستفادة المتوقعة من البرنامج']];
const seed={programs:[
{id:'PRG-1001',name:'معسكر الابتكار المؤسسي',type:'برنامج',date:'2026-07-15',audience:'موظفو الجامعة',participants:64,organizer:'مركز الابتكار وريادة الأعمال',trainer:'د. أحمد الحربي',description:'برنامج تطبيقي لتطوير الابتكار المؤسسي.'},
{id:'PRG-1002',name:'ورشة نمذجة الأفكار',type:'ورشة عمل',date:'2026-07-10',audience:'الطلاب ورواد الأعمال',participants:42,organizer:'مركز الابتكار وريادة الأعمال',trainer:'أ. سارة الغامدي',description:'ورشة عملية لتحويل الأفكار إلى نماذج أولية.'},
{id:'PRG-1003',name:'جلسة حوارية مع رائد أعمال',type:'جلسة',date:'2026-07-06',audience:'طلبة الجامعة',participants:95,organizer:'مركز الابتكار وريادة الأعمال',trainer:'م. خالد العمري',description:'جلسة مفتوحة حول بناء المشاريع الناشئة.'},
{id:'PRG-1004',name:'برنامج بناء المشاريع الناشئة',type:'برنامج',date:'2026-07-28',audience:'رواد الأعمال',participants:50,organizer:'مركز الابتكار وريادة الأعمال',trainer:'د. نورة الزهراني',description:'برنامج لتطوير نماذج الأعمال.'}],
evaluations:[],settings:{centerName:'مركز الابتكار وريادة الأعمال',universityName:'جامعة الملك عبدالعزيز'}};
function seededEvaluations(){const out=[];[['PRG-1001',44,4.7],['PRG-1002',28,4.5],['PRG-1003',53,4.4]].forEach(([id,count,avg])=>{for(let i=0;i<count;i++)out.push({id:crypto.randomUUID(),programId:id,content:clamp(avg+(Math.random()-.5)*.8),organization:clamp(avg+(Math.random()-.5)*.9),trainer:clamp(avg+(Math.random()-.5)*.7),goals:clamp(avg+(Math.random()-.5)*.8),benefit:clamp(avg+(Math.random()-.5)*.8),strengths:i%11===0?'وضوح المحتوى وتفاعل المدرب':'',comment:i%13===0?'نقترح زيادة الوقت المخصص للتطبيق العملي':'',createdAt:new Date().toISOString()});});return out}
function clamp(v){return Math.max(1,Math.min(5,Math.round(v)))}
let db=JSON.parse(localStorage.getItem(DB_KEY)||'null');if(!db){db=structuredClone(seed);db.evaluations=seededEvaluations();save()}
let currentProgramId=null,deleteTarget=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(DB_KEY,JSON.stringify(db))}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]))}
function formatDate(v){return new Intl.DateTimeFormat('ar-SA',{year:'numeric',month:'short',day:'numeric'}).format(new Date(v+'T12:00:00'))}
function status(p){return new Date(p.date+'T23:59:59')>=new Date()?'قادم':'مكتمل'}
function evaluationsFor(id){return db.evaluations.filter(e=>e.programId===id)}
function avg(list,key){if(!list.length)return null;return list.reduce((s,x)=>s+Number(x[key]||0),0)/list.length}
function overall(list){if(!list.length)return null;return questions.reduce((s,[k])=>s+avg(list,k),0)/questions.length}
function metrics(p){const list=evaluationsFor(p.id),score=overall(list),response=p.participants?Math.min(100,Math.round(list.length/p.participants*100)):0;return{list,score,response}}
const titles={dashboard:'لوحة المتابعة',programs:'البرامج والورش','new-program':'إضافة برنامج','program-details':'تفاصيل البرنامج',evaluations:'التقييمات',reports:'التقارير',settings:'الإعدادات'};
function navigate(id){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('#pageTitle').textContent=titles[id]||'';$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});if(id==='dashboard')renderDashboard();if(id==='programs')renderPrograms();if(id==='evaluations')renderEvaluations();if(id==='reports')renderReports();}
$$('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
function renderDashboard(){const participants=db.programs.reduce((s,p)=>s+Number(p.participants||0),0),responses=db.evaluations.length,allScore=overall(db.evaluations),rate=participants?Math.round(responses/participants*100):0;$('#programCount').textContent=db.programs.length;$('#participantCount').textContent=participants;$('#satisfactionAvg').textContent=allScore?allScore.toFixed(2):'—';$('#responseAvg').textContent=rate+'%';$('#donutValue').textContent=rate+'%';$('#responseDonut').style.background=`conic-gradient(var(--green-700) 0 ${rate}%,var(--green-100) ${rate}% 100%)`;$('#responseLegend').innerHTML=`<span><i class="legend-green"></i> تم التقييم ${responses}</span><span><i></i> لم يقيّم ${Math.max(0,participants-responses)}</span>`;
$('#recentPrograms').innerHTML=db.programs.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(p=>{const m=metrics(p);return `<tr class="clickable" onclick="openProgram('${p.id}')"><td><strong>${escapeHtml(p.name)}</strong><br><small>${escapeHtml(p.trainer)}</small></td><td>${p.type}</td><td>${formatDate(p.date)}</td><td>${p.participants}</td><td>${m.response}%</td><td><span class="score">${m.score?m.score.toFixed(2):'—'}</span></td><td><span class="status ${status(p)==='مكتمل'?'done':'upcoming'}">${status(p)}</span></td></tr>`}).join('');
const completed=db.programs.filter(p=>overall(evaluationsFor(p.id)));$('#satisfactionChart').innerHTML=completed.length?completed.slice(-6).map(p=>{const s=overall(evaluationsFor(p.id));return `<div title="${escapeHtml(p.name)}: ${s.toFixed(2)}"><span style="height:${s/5*100}%"></span><small>${escapeHtml(p.name.slice(0,12))}</small></div>`}).join(''):'<div class="muted">لا توجد تقييمات بعد</div>'}
function renderPrograms(list=db.programs){$('#programGrid').innerHTML=list.map(p=>{const m=metrics(p);return `<article class="program-card"><div class="program-card-top"><span class="type-chip">${p.type}</span><span class="status ${status(p)==='مكتمل'?'done':'upcoming'}">${status(p)}</span></div><h3>${escapeHtml(p.name)}</h3><p>المقدم: ${escapeHtml(p.trainer)}</p><p>التاريخ: ${formatDate(p.date)}</p><p>المشاركون: ${p.participants}</p><div class="program-card-footer"><span>الاستجابة ${m.response}%</span><span class="score">${m.score?m.score.toFixed(2)+' / 5':'لم يبدأ'}</span></div><div class="card-actions"><button onclick="openProgram('${p.id}')">عرض التفاصيل</button><button onclick="editProgram('${p.id}')">تعديل</button><button class="danger-link" onclick="askDelete('${p.id}')">حذف</button></div></article>`}).join('')||'<div class="empty-state"><h2>لا توجد نتائج</h2><p>غيّر كلمات البحث أو أضف برنامجًا جديدًا.</p></div>'}
function applyFilters(){const q=$('#programSearch').value.trim().toLowerCase(),type=$('#typeFilter').value,st=$('#statusFilter').value;renderPrograms(db.programs.filter(p=>(p.name+' '+p.trainer+' '+p.organizer).toLowerCase().includes(q)&&(type==='all'||p.type===type)&&(st==='all'||status(p)===st)))}
$('#programSearch').oninput=applyFilters;$('#typeFilter').onchange=applyFilters;$('#statusFilter').onchange=applyFilters;
$('#programForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),id=fd.get('id');const item={id:id||'PRG-'+Date.now(),name:fd.get('name').trim(),type:fd.get('type'),date:fd.get('date'),audience:fd.get('audience').trim(),participants:Number(fd.get('participants')),organizer:fd.get('organizer').trim(),trainer:fd.get('trainer').trim(),description:fd.get('description').trim()};if(id){const i=db.programs.findIndex(p=>p.id===id);db.programs[i]=item;showToast('تم تحديث بيانات البرنامج')}else{db.programs.unshift(item);showToast('تم إنشاء البرنامج ورابط التقييم')}save();resetForm();renderDashboard();renderPrograms();openProgram(item.id)};
function resetForm(){$('#programForm').reset();$('#programForm [name=id]').value='';$('#programFormTitle').textContent='إنشاء برنامج جديد'}$('#cancelEdit').onclick=resetForm;
window.editProgram=id=>{const p=db.programs.find(x=>x.id===id);if(!p)return;Object.entries(p).forEach(([k,v])=>{const el=$(`#programForm [name="${k}"]`);if(el)el.value=v});$('#programFormTitle').textContent='تعديل البرنامج';navigate('new-program')};
window.openProgram=id=>{const p=db.programs.find(x=>x.id===id);if(!p)return;currentProgramId=id;const m=metrics(p),link=`${location.href.split('#')[0]}#evaluate=${encodeURIComponent(id)}`;$('#programDetails').innerHTML=`<div class="section-tools"><div><p class="eyebrow">${p.id}</p><h2>${escapeHtml(p.name)}</h2></div><div class="inline-actions"><button class="secondary-btn" onclick="editProgram('${p.id}')">تعديل</button><button class="primary-btn" onclick="openEvaluation('${p.id}')">فتح نموذج التقييم</button></div></div><div class="detail-grid"><article class="panel detail-card"><h3>بيانات البرنامج</h3><dl><div><dt>النوع</dt><dd>${p.type}</dd></div><div><dt>التاريخ</dt><dd>${formatDate(p.date)}</dd></div><div><dt>الفئة المستهدفة</dt><dd>${escapeHtml(p.audience)}</dd></div><div><dt>عدد المشاركين</dt><dd>${p.participants}</dd></div><div><dt>الجهة المنظمة</dt><dd>${escapeHtml(p.organizer)}</dd></div><div><dt>المدرب</dt><dd>${escapeHtml(p.trainer)}</dd></div></dl><p class="muted">${escapeHtml(p.description||'لا يوجد وصف.')}</p></article><article class="panel detail-card"><h3>رابط التقييم</h3><div class="qr-box"><img alt="QR" src="https://quickchart.io/qr?size=180&text=${encodeURIComponent(link)}"><div><input class="link-input" value="${escapeHtml(link)}" readonly><div class="inline-actions"><button class="secondary-btn" onclick="copyLink('${encodeURIComponent(link)}')">نسخ الرابط</button><button class="primary-btn" onclick="shareLink('${p.id}')">مشاركة</button></div></div></div></article></div><div class="kpi-grid"><article class="kpi-card"><div><small>عدد الردود</small><strong>${m.list.length}</strong></div></article><article class="kpi-card"><div><small>نسبة الاستجابة</small><strong>${m.response}%</strong></div></article><article class="kpi-card"><div><small>متوسط الرضا</small><strong>${m.score?m.score.toFixed(2):'—'}</strong></div></article><article class="kpi-card"><div><small>الحالة</small><strong class="small-value">${status(p)}</strong></div></article></div>${renderProgramResults(p,m.list)}`;navigate('program-details')};
function renderProgramResults(p,list){if(!list.length)return '<div class="empty-state compact"><h2>لا توجد تقييمات حتى الآن</h2><p>شارك الرابط أو رمز QR مع المشاركين بعد انتهاء البرنامج.</p></div>';return `<article class="panel table-panel"><div class="panel-head"><div><small>تحليل المحاور</small><h3>نتائج التقييم</h3></div></div><div class="axis-grid">${questions.map(([k,l])=>`<div><span>${l}</span><strong>${avg(list,k).toFixed(2)}</strong><div class="progress"><i style="width:${avg(list,k)/5*100}%"></i></div></div>`).join('')}</div></article><article class="panel notes-panel"><h3>الملاحظات والمقترحات</h3>${list.filter(x=>x.comment||x.strengths).map(x=>`<div class="comment-card">${x.strengths?`<strong>نقطة قوة: ${escapeHtml(x.strengths)}</strong>`:''}${x.comment?`<p>${escapeHtml(x.comment)}</p>`:''}</div>`).join('')||'<p class="muted">لا توجد ملاحظات نصية.</p>'}</article>`}
window.copyLink=async encoded=>{await navigator.clipboard.writeText(decodeURIComponent(encoded));showToast('تم نسخ رابط التقييم')};window.shareLink=async id=>{const p=db.programs.find(x=>x.id===id),url=`${location.href.split('#')[0]}#evaluate=${id}`;if(navigator.share)await navigator.share({title:`تقييم ${p.name}`,text:'نرجو تقييم مشاركتكم في البرنامج',url});else{await navigator.clipboard.writeText(url);showToast('تم نسخ الرابط للمشاركة')}};
window.openEvaluation=id=>{const p=db.programs.find(x=>x.id===id)||db.programs[0];if(!p)return;$('#evaluationTitle').textContent='تقييم: '+p.name;$('#evaluationForm [name=programId]').value=p.id;$('#ratingQuestions').innerHTML=questions.map(([k,l])=>`<label>${l}<div class="rating-row" data-name="${k}">${[1,2,3,4,5].map(n=>`<button type="button" data-value="${n}">${n}</button>`).join('')}</div><input type="hidden" name="${k}" required></label>`).join('');$$('.rating-row button').forEach(btn=>btn.onclick=()=>{const row=btn.parentElement;row.querySelectorAll('button').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');row.nextElementSibling.value=btn.dataset.value});$('#evaluationModal').classList.add('show')};
$('#previewEvaluation').onclick=()=>openEvaluation(db.programs[0]?.id);$('#closeModal').onclick=()=>$('#evaluationModal').classList.remove('show');$('#evaluationModal').onclick=e=>{if(e.target.id==='evaluationModal')e.currentTarget.classList.remove('show')};
$('#evaluationForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget);if(questions.some(([k])=>!fd.get(k))){showToast('قيّم جميع المحاور أولًا');return}const entry={id:crypto.randomUUID(),programId:fd.get('programId'),createdAt:new Date().toISOString(),strengths:fd.get('strengths').trim(),comment:fd.get('comment').trim()};questions.forEach(([k])=>entry[k]=Number(fd.get(k)));db.evaluations.push(entry);save();e.currentTarget.reset();$('#evaluationModal').classList.remove('show');showToast('شكرًا، تم حفظ التقييم');renderDashboard();if(currentProgramId===entry.programId)openProgram(entry.programId)};
function renderEvaluations(){$('#evaluationPrograms').innerHTML=db.programs.map(p=>{const m=metrics(p);return `<tr><td><strong>${escapeHtml(p.name)}</strong></td><td>${m.list.length}</td><td>${m.response}%</td><td>${m.score?m.score.toFixed(2):'—'}</td><td><button class="text-btn" onclick="openProgram('${p.id}')">عرض النتائج</button> <button class="text-btn" onclick="openEvaluation('${p.id}')">فتح النموذج</button></td></tr>`}).join('')}
function renderReports(){const scored=db.programs.filter(p=>metrics(p).score),best=scored.sort((a,b)=>metrics(b).score-metrics(a).score)[0],all=overall(db.evaluations),participants=db.programs.reduce((s,p)=>s+p.participants,0),rate=participants?Math.round(db.evaluations.length/participants*100):0;$('#reportKpis').innerHTML=`<article class="kpi-card"><div><small>متوسط الرضا العام</small><strong>${all?all.toFixed(2):'—'}</strong></div></article><article class="kpi-card"><div><small>نسبة المشاركة</small><strong>${rate}%</strong></div></article><article class="kpi-card"><div><small>أفضل برنامج</small><strong class="small-value">${best?escapeHtml(best.name):'—'}</strong></div></article><article class="kpi-card"><div><small>إجمالي الردود</small><strong>${db.evaluations.length}</strong></div></article>`;$('#reportsTable').innerHTML=db.programs.map(p=>{const l=evaluationsFor(p.id);return `<tr><td>${escapeHtml(p.name)}</td>${questions.map(([k])=>`<td>${l.length?avg(l,k).toFixed(2):'—'}</td>`).join('')}<td><strong>${l.length?overall(l).toFixed(2):'—'}</strong></td></tr>`}).join('');const notes=db.evaluations.filter(e=>e.comment||e.strengths);$('#commentsList').innerHTML=notes.slice().reverse().slice(0,20).map(e=>{const p=db.programs.find(x=>x.id===e.programId);return `<div class="comment-card"><small>${escapeHtml(p?.name||'برنامج محذوف')}</small>${e.strengths?`<strong>نقطة قوة: ${escapeHtml(e.strengths)}</strong>`:''}${e.comment?`<p>${escapeHtml(e.comment)}</p>`:''}</div>`}).join('')||'<p class="muted">لا توجد ملاحظات بعد.</p>'}
$('#exportCsv').onclick=()=>{const rows=[['رقم البرنامج','اسم البرنامج','النوع','المشاركون','الردود','نسبة الاستجابة','متوسط الرضا'],...db.programs.map(p=>{const m=metrics(p);return[p.id,p.name,p.type,p.participants,m.list.length,m.response,m.score?m.score.toFixed(2):'']})];download('\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n'),'iec-report.csv','text/csv')};
function download(data,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function askDelete(id){deleteTarget=id;$('#confirmModal').classList.add('show')}window.askDelete=askDelete;$('#cancelDelete').onclick=()=>$('#confirmModal').classList.remove('show');$('#confirmDelete').onclick=()=>{db.programs=db.programs.filter(p=>p.id!==deleteTarget);db.evaluations=db.evaluations.filter(e=>e.programId!==deleteTarget);save();$('#confirmModal').classList.remove('show');renderPrograms();renderDashboard();showToast('تم حذف البرنامج')};
$('#saveSettings').onclick=()=>{db.settings.centerName=$('#centerName').value.trim();db.settings.universityName=$('#universityName').value.trim();save();showToast('تم حفظ الإعدادات')};$('#backupData').onclick=()=>download(JSON.stringify(db,null,2),'iec-backup.json','application/json');$('#resetData').onclick=()=>{if(confirm('سيتم حذف البيانات الحالية وإعادة بيانات التجربة.')){db=structuredClone(seed);db.evaluations=seededEvaluations();save();location.reload()}};
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
window.addEventListener('hashchange',()=>{const m=location.hash.match(/^#evaluate=(.+)$/);if(m)openEvaluation(decodeURIComponent(m[1]))});
renderDashboard();renderPrograms();renderEvaluations();renderReports();$('#centerName').value=db.settings.centerName;$('#universityName').value=db.settings.universityName;if(location.hash.startsWith('#evaluate='))openEvaluation(decodeURIComponent(location.hash.split('=')[1]));
if(!document.querySelector('link[href="completion-features.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='completion-features.css';document.head.appendChild(l)}
if(!document.querySelector('script[src="completion-features.js"]')){const s=document.createElement('script');s.src='completion-features.js';document.body.appendChild(s)}