(()=>{
  const defaultQuestions=[
    {id:'content',label:'ما مدى رضاك عن محتوى البرنامج؟',type:'rating',required:true},
    {id:'organization',label:'ما مدى رضاك عن تنظيم البرنامج؟',type:'rating',required:true},
    {id:'trainer',label:'كيف تقيّم المدرب أو مقدم الجلسة؟',type:'rating',required:true},
    {id:'goals',label:'إلى أي مدى تحققت أهداف البرنامج؟',type:'rating',required:true},
    {id:'benefit',label:'ما مدى استفادتك من البرنامج؟',type:'rating',required:true},
    {id:'strengths',label:'ما أبرز نقاط القوة في البرنامج؟',type:'long',required:false},
    {id:'comment',label:'هل لديك ملاحظات أو مقترحات؟',type:'long',required:false}
  ];
  if(!document.querySelector('link[href="question-bank.css"]')){const css=document.createElement('link');css.rel='stylesheet';css.href='question-bank.css';document.head.appendChild(css)}
  if(!document.querySelector('[data-view="question-bank"]')){const btn=document.createElement('button');btn.className='nav-item';btn.dataset.view='question-bank';btn.innerHTML='<span>؟</span> بنك الأسئلة';document.querySelector('.nav-list')?.insertBefore(btn,document.querySelector('[data-view="settings"]'))}
  if(!document.querySelector('#question-bank')){const section=document.createElement('section');section.id='question-bank';section.className='view';section.innerHTML=`<div class="section-tools"><div><p class="eyebrow">إدارة نماذج التقييم</p><h2>بنك أسئلة التقييم</h2></div></div><div class="question-bank-layout"><aside class="panel question-bank-side"><label>النموذج الذي تريد تعديله<select id="questionScope"></select></label><p class="question-scope-note">النموذج الافتراضي يُنسخ تلقائيًا عند إنشاء برنامج جديد. ويمكنك بعد ذلك تخصيص أسئلة أي برنامج بشكل مستقل.</p><button class="secondary-btn" id="copyDefaultQuestions">تطبيق الأسئلة الافتراضية على هذا البرنامج</button></aside><article class="panel question-bank-main"><div class="panel-head"><div><small>الأسئلة الحالية</small><h3>إضافة وتعديل وترتيب الأسئلة</h3></div></div><div id="questionList" class="question-list"></div><div class="question-editor"><input id="questionTitleInput" placeholder="اكتب نص السؤال"/><select id="questionTypeInput"><option value="rating">تقييم من 1 إلى 5</option><option value="yesno">نعم / لا</option><option value="short">إجابة قصيرة</option><option value="long">إجابة طويلة</option></select><select id="questionRequiredInput"><option value="true">إلزامي</option><option value="false">اختياري</option></select><div class="editor-actions"><button class="secondary-btn" id="cancelQuestionEdit" type="button">إلغاء</button><button class="primary-btn" id="saveQuestionBtn" type="button">إضافة السؤال</button></div></div></article></div>`;document.querySelector('main.main-content')?.appendChild(section)}
  if(!Array.isArray(db.questionBank)||!db.questionBank.length) db.questionBank=structuredClone(defaultQuestions);
  db.programs.forEach(p=>{if(!Array.isArray(p.questionnaire)||!p.questionnaire.length)p.questionnaire=structuredClone(db.questionBank)});save();
  function syncLegacyQuestions(){const ratings=db.questionBank.filter(q=>q.type==='rating').map(q=>[q.id,q.label]);questions.splice(0,questions.length,...ratings)}syncLegacyQuestions();
  const scope=document.querySelector('#questionScope'),list=document.querySelector('#questionList'),titleInput=document.querySelector('#questionTitleInput'),typeInput=document.querySelector('#questionTypeInput'),requiredInput=document.querySelector('#questionRequiredInput'),saveBtn=document.querySelector('#saveQuestionBtn'),cancelBtn=document.querySelector('#cancelQuestionEdit');let editingId=null;
  function currentQuestions(){if(scope.value==='default')return db.questionBank;return db.programs.find(p=>p.id===scope.value)?.questionnaire||[]}
  function persist(){save();syncLegacyQuestions();render();renderDashboard();renderEvaluations();renderReports()}
  function resetEditor(){editingId=null;titleInput.value='';typeInput.value='rating';requiredInput.value='true';saveBtn.textContent='إضافة السؤال'}
  function typeLabel(type){return({rating:'تقييم من 1 إلى 5',yesno:'نعم / لا',short:'إجابة قصيرة',long:'إجابة طويلة'})[type]||type}
  function renderScope(){const selected=scope.value||'default';scope.innerHTML='<option value="default">النموذج الافتراضي للبرامج الجديدة</option>'+db.programs.map(p=>`<option value="${p.id}">${escapeHtml(p.name)}</option>`).join('');scope.value=[...scope.options].some(o=>o.value===selected)?selected:'default'}
  function render(){renderScope();const qs=currentQuestions();list.innerHTML=qs.length?qs.map((q,i)=>`<div class="question-item"><span class="question-number">${i+1}</span><div><h4>${escapeHtml(q.label)}${q.required?'<span class="required-chip">إلزامي</span>':''}</h4><small>${typeLabel(q.type)}</small></div><div class="question-actions"><button data-up="${q.id}" ${i===0?'disabled':''}>↑</button><button data-down="${q.id}" ${i===qs.length-1?'disabled':''}>↓</button><button data-edit="${q.id}">تعديل</button><button class="delete-question" data-delete="${q.id}">حذف</button></div></div>`).join(''):'<div class="question-empty">لا توجد أسئلة في هذا النموذج.</div>'}
  function findQuestion(id){return currentQuestions().find(q=>q.id===id)}
  function move(id,dir){const qs=currentQuestions(),i=qs.findIndex(q=>q.id===id),j=i+dir;if(i<0||j<0||j>=qs.length)return;[qs[i],qs[j]]=[qs[j],qs[i]];persist()}
  function remove(id){const qs=currentQuestions(),i=qs.findIndex(q=>q.id===id);if(i<0||!confirm('هل تريد حذف هذا السؤال؟'))return;qs.splice(i,1);persist();resetEditor()}
  function edit(id){const q=findQuestion(id);if(!q)return;editingId=id;titleInput.value=q.label;typeInput.value=q.type;requiredInput.value=String(q.required);saveBtn.textContent='حفظ التعديل';titleInput.focus()}
  list.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.up)move(b.dataset.up,-1);if(b.dataset.down)move(b.dataset.down,1);if(b.dataset.edit)edit(b.dataset.edit);if(b.dataset.delete)remove(b.dataset.delete)};
  scope.onchange=()=>{resetEditor();render()};
  saveBtn.onclick=()=>{const label=titleInput.value.trim();if(!label){showToast('اكتب نص السؤال أولًا');return}const qs=currentQuestions(),wasEditing=Boolean(editingId);if(editingId){const q=findQuestion(editingId);q.label=label;q.type=typeInput.value;q.required=requiredInput.value==='true'}else qs.push({id:'Q-'+Date.now(),label,type:typeInput.value,required:requiredInput.value==='true'});persist();resetEditor();showToast(wasEditing?'تم تعديل السؤال':'تمت إضافة السؤال')};
  cancelBtn.onclick=resetEditor;
  document.querySelector('#copyDefaultQuestions').onclick=()=>{if(scope.value==='default'){showToast('أنت داخل النموذج الافتراضي بالفعل');return}const p=db.programs.find(x=>x.id===scope.value);p.questionnaire=structuredClone(db.questionBank);persist();showToast('تم تطبيق الأسئلة الافتراضية على البرنامج')};
  const nav=document.querySelector('[data-view="question-bank"]');nav.onclick=()=>{navigate('question-bank');document.querySelector('#pageTitle').textContent='بنك أسئلة التقييم';render()};
  document.querySelector('#programForm').addEventListener('submit',()=>setTimeout(()=>{let changed=false;db.programs.forEach(p=>{if(!Array.isArray(p.questionnaire)||!p.questionnaire.length){p.questionnaire=structuredClone(db.questionBank);changed=true}});if(changed)save();renderScope()},0));
  render();
})();